### ISSUE TITLE
Add media type for Controller Documents

### ISSUE THREAD

**Issue by msporny** [w3c/cid#127]
The current specification does not have an IANA considerations section to register a media type. The suggested media type is: `application/controller`.

**Comment by longpd** [comment]
+1 for this media type (application/controller)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-11-20-vcwg#section1-8) on 2024-11-20

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.8. Add media type for Controller Documents (issue controller-document#127)

_See github issue [controller-document#127](https://github.com/w3c/controller-document/issues/127)._




**Brent Zundel:** I do not see any conflicts with media type application/controller.  

**Manu Sporny:** This is just a request to the group. What do you think about application/controller? I can raise a PR with IANA to register it.  

**Ivan Herman:** I have no problem with application/controller. I don't really understand how these things work.  
… The DID document is essentially a controller document. We define it as application/did.  

**David Chadwick:** I made a comment on another issue. Manu said that there was no clear consensus on changing the name, I pointed out that there was on the last meeting.  

**Brent Zundel:** It was my call, as chair, that while there was consensus that we didn't like controller document, there was no consensus on an alternative.  

**Joe Andrieu:** I agree with DavidC. I do have a sustained objection to an incorrect call about consensus and I will be filing a formal objection.  

**Brent Zundel:** It sounds like we're reopening the renaming conversation.  

> *David Chadwick:* +1 JoeAndrieu.

**Joe Andrieu:** Not one person voted against renaming to Identifier Document.  

> *Joe Andrieu:* +1 to getting the PR proposed.

**Manu Sporny:** I'm going to raise a PR, put application/controller in it. People can comment and we can change to application/identifier or something else in the PR.  

> **Proposed resolution: rename the Controller document to Identifier document.** *(Brent Zundel)*

> *David Chadwick:* I also said that application/identifier would be more appropriate than application/controller and it would better align with application/did.

**Brent Zundel:** I don't care.  

> *Gabe Cohen:* +0.

> *Brent Zundel:* +0.

**Joe Andrieu:** Apparently you do.  

**Brent Zundel:** Show me the consensus.  

> *David Chadwick:* Look at the minutes of the last meeting and the voting.

**Joe Andrieu:** I don't think this is a valid proposal. This is my objection to you as chair, you shut down conversation.  

**Brent Zundel:** I'm allowed to say I don't want to talk about something. Yet, we have. On the calls, on the issues, in the PRs. I have not seen any suggestion made that had universal agreement.  
… I said we shouldn't discuss it any further because we can't come to agreement. I am doing so in my duty as chair to say that we don't have consensus and we have to move on.  
… Making a resolution today doesn't shut anything down.  
… There's a proposal on the table to change the name.  

> *David Chadwick:* Brent look at the voting from last week.

**Brent Zundel:** If I didn't see the consensus before, show it to me now.  

> *Manu Sporny:* +0 (due to something Longley said last week that was of concern to me -- would like to discuss why "Identifier Document" isn't the right word).

**Brent Zundel:** The proposal is on the table.  

> *Dave Longley:* +0 (will not block) would prefer Controlled/Controllable in there because Identifier Document is lacking to me.

> *Joe Andrieu:* +1.

> *David Chadwick:* +1.

**Brent Zundel:** I see three zeros. I don't see any plus ones.  

**Ted Thibodeau Jr.:** We're at time. We'll be past it if we go further.  

> *Phillip Long:* As I understand Manu's suggestion the discussion about this was to take place in the PR.

> *Joe Andrieu:* Let the record show that no one objected.

**Brent Zundel:** I see four zeros and two plus ones. We'll come back after Thanksgiving and set an entire meeting to this topic if that's what's necessary.  
… Tell me what you want and I'll make it happen.  

**Joe Andrieu:** There is no objection to this poll.  

---

</details>

**Comment by msporny** [comment]
PR #129 has been raised to address this issue. This issue will be closed once PR #129 has been merged.

**Comment by msporny** [comment]
PR #129 has been merged, closing.
